//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.Clock.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class NominationDictionary {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NominationDictionary() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTS.Clock.Model.NominationDictionary", typeof(NominationDictionary).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConceptValueList.
        /// </summary>
        internal static string CnpValueList {
            get {
                return ResourceManager.GetString("CnpValueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefinedRule.
        /// </summary>
        internal static string DefRle {
            get {
                return ResourceManager.GetString("DefRle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectCategory.
        /// </summary>
        internal static string ObjCat {
            get {
                return ResourceManager.GetString("ObjCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrganChart.
        /// </summary>
        internal static string OrgCh {
            get {
                return ResourceManager.GetString("OrgCh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PairableSecondaryConceptValuePair.
        /// </summary>
        internal static string PairScndCnpValuePair {
            get {
                return ResourceManager.GetString("PairScndCnpValuePair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        internal static string Prs {
            get {
                return ResourceManager.GetString("Prs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonAssignment.
        /// </summary>
        internal static string PrsAsg {
            get {
                return ResourceManager.GetString("PrsAsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PersonUnit.
        /// </summary>
        internal static string PrsUnit {
            get {
                return ResourceManager.GetString("PrsUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RuleConcept.
        /// </summary>
        internal static string RleCnp {
            get {
                return ResourceManager.GetString("RleCnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondaryConcept.
        /// </summary>
        internal static string ScndCnp {
            get {
                return ResourceManager.GetString("ScndCnp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondaryConceptValue.
        /// </summary>
        internal static string ScndCnpValue {
            get {
                return ResourceManager.GetString("ScndCnpValue", resourceCulture);
            }
        }
    }
}
