//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.Clock.Business.GTSEngineWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GTSEngineWS.ITotalWebService")]
    public interface ITotalWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_ExecuteByPersonID", ReplyAction="http://tempuri.org/ITotalWebService/GTS_ExecuteByPersonIDResponse")]
        void GTS_ExecuteByPersonID(string CallerIdentity, decimal PersonId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_ExecuteByPersonIdAndToDate", ReplyAction="http://tempuri.org/ITotalWebService/GTS_ExecuteByPersonIdAndToDateResponse")]
        bool GTS_ExecuteByPersonIdAndToDate(string CallerIdentity, decimal PersonId, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITotalWebService/GTS_ExecuteAll")]
        void GTS_ExecuteAll(string CallerIdentity);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ITotalWebService/GTS_ExecuteAllByToDate")]
        void GTS_ExecuteAllByToDate(string CallerIdentity, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_ExecutePersonsByToDate", ReplyAction="http://tempuri.org/ITotalWebService/GTS_ExecutePersonsByToDateResponse")]
        bool GTS_ExecutePersonsByToDate(string CallerIdentity, decimal[] Persons, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_ExecutePersonsByToDateGUID", ReplyAction="http://tempuri.org/ITotalWebService/GTS_ExecutePersonsByToDateGUIDResponse")]
        bool GTS_ExecutePersonsByToDateGUID(string CallerIdentity, string operationGUID, System.DateTime Date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_GETTotalExecuting", ReplyAction="http://tempuri.org/ITotalWebService/GTS_GETTotalExecutingResponse")]
        int GTS_GETTotalExecuting(string CallerIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_GETRemainExecuting", ReplyAction="http://tempuri.org/ITotalWebService/GTS_GETRemainExecutingResponse")]
        int GTS_GETRemainExecuting(string CallerIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_GETTotalErrorExecuting", ReplyAction="http://tempuri.org/ITotalWebService/GTS_GETTotalErrorExecutingResponse")]
        int GTS_GETTotalErrorExecuting(string CallerIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_LockCalculation", ReplyAction="http://tempuri.org/ITotalWebService/GTS_LockCalculationResponse")]
        bool GTS_LockCalculation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITotalWebService/GTS_UnLockCalculation", ReplyAction="http://tempuri.org/ITotalWebService/GTS_UnLockCalculationResponse")]
        bool GTS_UnLockCalculation();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITotalWebServiceChannel : GTS.Clock.Business.GTSEngineWS.ITotalWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TotalWebServiceClient : System.ServiceModel.ClientBase<GTS.Clock.Business.GTSEngineWS.ITotalWebService>, GTS.Clock.Business.GTSEngineWS.ITotalWebService {
        
        public TotalWebServiceClient() {
        }
        
        public TotalWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TotalWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TotalWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TotalWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GTS_ExecuteByPersonID(string CallerIdentity, decimal PersonId) {
            base.Channel.GTS_ExecuteByPersonID(CallerIdentity, PersonId);
        }
        
        public bool GTS_ExecuteByPersonIdAndToDate(string CallerIdentity, decimal PersonId, System.DateTime Date) {
            return base.Channel.GTS_ExecuteByPersonIdAndToDate(CallerIdentity, PersonId, Date);
        }
        
        public void GTS_ExecuteAll(string CallerIdentity) {
            base.Channel.GTS_ExecuteAll(CallerIdentity);
        }
        
        public void GTS_ExecuteAllByToDate(string CallerIdentity, System.DateTime Date) {
            base.Channel.GTS_ExecuteAllByToDate(CallerIdentity, Date);
        }
        
        public bool GTS_ExecutePersonsByToDate(string CallerIdentity, decimal[] Persons, System.DateTime Date) {
            return base.Channel.GTS_ExecutePersonsByToDate(CallerIdentity, Persons, Date);
        }
        
        public bool GTS_ExecutePersonsByToDateGUID(string CallerIdentity, string operationGUID, System.DateTime Date) {
            return base.Channel.GTS_ExecutePersonsByToDateGUID(CallerIdentity, operationGUID, Date);
        }
        
        public int GTS_GETTotalExecuting(string CallerIdentity) {
            return base.Channel.GTS_GETTotalExecuting(CallerIdentity);
        }
        
        public int GTS_GETRemainExecuting(string CallerIdentity) {
            return base.Channel.GTS_GETRemainExecuting(CallerIdentity);
        }
        
        public int GTS_GETTotalErrorExecuting(string CallerIdentity) {
            return base.Channel.GTS_GETTotalErrorExecuting(CallerIdentity);
        }
        
        public bool GTS_LockCalculation() {
            return base.Channel.GTS_LockCalculation();
        }
        
        public bool GTS_UnLockCalculation() {
            return base.Channel.GTS_UnLockCalculation();
        }
    }
}
