
function GridUnderManagementPersonnelExeptionAccessView_UnderManagementPersonnelExeptionAccessView_onItemSelect(sender, e) { 
}

function GridUnderManagementPersonnelExeptionAccessView_UnderManagementPersonnelExeptionAccessView_onItemExpand(sender, e) {
    GridUnderManagementPersonnelExeptionAccessView_UnderManagementPersonnelExeptionAccessView.render();
}

function GridUnderManagementPersonnelExeptionAccessView_UnderManagementPersonnelExeptionAccessView_onItemCollapse(sender, e) { 
}
