//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CalculationRange {
    
    /// <summary>
    /// CalculationRangeForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm CalculationRangeForm;
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// TlbCalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbCalculationRange;
    
    /// <summary>
    /// tlbItemEndorsement_TlbCalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemEndorsement_TlbCalculationRange;
    
    /// <summary>
    /// tlbItemDecreaseAll_TlbCalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemDecreaseAll_TlbCalculationRange;
    
    /// <summary>
    /// tlbItemIncreaseAll_TlbCalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemIncreaseAll_TlbCalculationRange;
    
    /// <summary>
    /// tlbItemFormReconstruction_TlbCalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFormReconstruction_TlbCalculationRange;
    
    /// <summary>
    /// tlbItemExit_TlbCalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbCalculationRange;
    
    /// <summary>
    /// SelectAll_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label SelectAll_CalculationRange;
    
    /// <summary>
    /// TlbRefresh_GridConcepts_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_GridConcepts_CalculationRange;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_GridConcepts_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridConcepts_CalculationRange;
    
    /// <summary>
    /// CallBack_GridConcepts_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_GridConcepts_CalculationRange;
    
    /// <summary>
    /// GridConcepts_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.DataGrid GridConcepts_CalculationRange;
    
    /// <summary>
    /// ErrorHiddenField_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_CalculationRange;
    
    /// <summary>
    /// CheckListHiddenField_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField CheckListHiddenField_CalculationRange;
    
    /// <summary>
    /// header_CalculationRangeDetails_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl header_CalculationRangeDetails_CalculationRange;
    
    /// <summary>
    /// lblCalculationRangeName_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblCalculationRangeName_CalculationRange;
    
    /// <summary>
    /// lblDescription_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblDescription_CalculationRange;
    
    /// <summary>
    /// lblMonth1_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth1_CalculationRange;
    
    /// <summary>
    /// lblMonth2_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth2_CalculationRange;
    
    /// <summary>
    /// lblMonth3_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth3_CalculationRange;
    
    /// <summary>
    /// lblMonth4_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth4_CalculationRange;
    
    /// <summary>
    /// lblMonth5_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth5_CalculationRange;
    
    /// <summary>
    /// lblMonth6_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth6_CalculationRange;
    
    /// <summary>
    /// lblMonth7_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth7_CalculationRange;
    
    /// <summary>
    /// lblMonth8_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth8_CalculationRange;
    
    /// <summary>
    /// lblMonth9_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth9_CalculationRange;
    
    /// <summary>
    /// lblMonth10_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth10_CalculationRange;
    
    /// <summary>
    /// lblMonth11_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth11_CalculationRange;
    
    /// <summary>
    /// lblMonth12_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth12_CalculationRange;
    
    /// <summary>
    /// DialogConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogConfirm;
    
    /// <summary>
    /// lblConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblConfirm;
    
    /// <summary>
    /// TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOkConfirm;
    
    /// <summary>
    /// tlbItemOk_TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOk_TlbOkConfirm;
    
    /// <summary>
    /// TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbCancelConfirm;
    
    /// <summary>
    /// tlbItemCancel_TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbCancelConfirm;
    
    /// <summary>
    /// DialogWaiting control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
    
    /// <summary>
    /// Img1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
    
    /// <summary>
    /// hfheader_CalculationRange_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_CalculationRange_CalculationRange;
    
    /// <summary>
    /// hfheader_CalculationRangeDetails_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_CalculationRangeDetails_CalculationRange;
    
    /// <summary>
    /// hfCloseMessage_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCloseMessage_CalculationRange;
    
    /// <summary>
    /// hfloadingPanel_GridConcepts_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridConcepts_CalculationRange;
    
    /// <summary>
    /// hfTitle_DialogCalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfTitle_DialogCalculationRange;
    
    /// <summary>
    /// hfAdd_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfAdd_CalculationRange;
    
    /// <summary>
    /// hfEdit_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfEdit_CalculationRange;
    
    /// <summary>
    /// hfErrorType_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfErrorType_CalculationRange;
    
    /// <summary>
    /// hfConnectionError_CalculationRange control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_CalculationRange;
}
