//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Date_Time_ReportParameter {
    
    /// <summary>
    /// Date_Time_ReportParameterForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm Date_Time_ReportParameterForm;
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// lblDate_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblDate_Date_Time_ReportParameter;
    
    /// <summary>
    /// Container_pdpDate_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Container_pdpDate_Date_Time_ReportParameter;
    
    /// <summary>
    /// pdpDate_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AspNetPersianDatePickup.PersianDatePickup pdpDate_Date_Time_ReportParameter;
    
    /// <summary>
    /// Container_gdpDate_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Container_gdpDate_Date_Time_ReportParameter;
    
    /// <summary>
    /// gdpDate_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Calendar gdpDate_ReportParameter;
    
    /// <summary>
    /// gCalDate_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Calendar gCalDate_Date_Time_ReportParameter;
    
    /// <summary>
    /// TlbRegister_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRegister_Date_Time_ReportParameter;
    
    /// <summary>
    /// tlbItemRegister_TlbRegister_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRegister_TlbRegister_Date_Time_ReportParameter;
    
    /// <summary>
    /// lblTime_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblTime_Date_Time_ReportParameter;
    
    /// <summary>
    /// DialogWaiting control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
    
    /// <summary>
    /// Img1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
    
    /// <summary>
    /// hfCurrentDate_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCurrentDate_Date_Time_ReportParameter;
    
    /// <summary>
    /// hfConnectionError_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_Date_Time_ReportParameter;
    
    /// <summary>
    /// hfErrorType_Date_Time_ReportParameter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfErrorType_Date_Time_ReportParameter;
    
    /// <summary>
    /// ReportParameterID control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ReportParameterID;
}
