//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.Clock.Presentaion.WebForms {
    
    
    public partial class EmployTypes {
        
        /// <summary>
        /// EmployTypesForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm EmployTypesForm;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbEmployTypesIntroduction;
        
        /// <summary>
        /// tlbItemNew_TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemNew_TlbEmployTypesIntroduction;
        
        /// <summary>
        /// tlbItemEdit_TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemEdit_TlbEmployTypesIntroduction;
        
        /// <summary>
        /// tlbItemDelete_TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemDelete_TlbEmployTypesIntroduction;
        
        /// <summary>
        /// tlbItemHelp_TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemHelp_TlbEmployTypesIntroduction;
        
        /// <summary>
        /// tlbItemSave_TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSave_TlbEmployTypesIntroduction;
        
        /// <summary>
        /// tlbItemCancel_TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbEmployTypesIntroduction;
        
        /// <summary>
        /// tlbItemFormReconstruction_TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFormReconstruction_TlbEmployTypesIntroduction;
        
        /// <summary>
        /// tlbItemExit_TlbEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbEmployTypesIntroduction;
        
        /// <summary>
        /// TlbRefresh_GridEmployTypes_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_GridEmployTypes_EmployTypes;
        
        /// <summary>
        /// tlbItemRefresh_TlbRefresh_GridEmployTypes_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridEmployTypes_EmployTypes;
        
        /// <summary>
        /// CallBack_GridEmployTypes_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_GridEmployTypes_EmployTypes;
        
        /// <summary>
        /// GridEmployTypes_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.DataGrid GridEmployTypes_EmployTypes;
        
        /// <summary>
        /// ErrorHiddenField_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_EmployTypes;
        
        /// <summary>
        /// Tr4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow Tr4;
        
        /// <summary>
        /// Td9 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Td9;
        
        /// <summary>
        /// header_tblEmployTypeDetails_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl header_tblEmployTypeDetails_EmployTypes;
        
        /// <summary>
        /// lblEmployCode_EmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEmployCode_EmployTypesIntroduction;
        
        /// <summary>
        /// txtEmployCode_EmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtEmployCode_EmployTypesIntroduction;
        
        /// <summary>
        /// lblEmployType_EmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblEmployType_EmployTypesIntroduction;
        
        /// <summary>
        /// txtEmployType_EmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtEmployType_EmployTypesIntroduction;
        
        /// <summary>
        /// DialogConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogConfirm;
        
        /// <summary>
        /// lblConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblConfirm;
        
        /// <summary>
        /// TlbOkConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbOkConfirm;
        
        /// <summary>
        /// tlbItemOk_TlbOkConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOk_TlbOkConfirm;
        
        /// <summary>
        /// TlbCancelConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbCancelConfirm;
        
        /// <summary>
        /// tlbItemCancel_TlbCancelConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbCancelConfirm;
        
        /// <summary>
        /// DialogWaiting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
        
        /// <summary>
        /// Img1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
        
        /// <summary>
        /// hfheader_tblEmployTypeDetails_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_tblEmployTypeDetails_EmployTypes;
        
        /// <summary>
        /// hfheader_EmployTypes_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_EmployTypes_EmployTypes;
        
        /// <summary>
        /// hfView_EmployType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfView_EmployType;
        
        /// <summary>
        /// hfAdd_EmployType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfAdd_EmployType;
        
        /// <summary>
        /// hfEdit_EmployType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfEdit_EmployType;
        
        /// <summary>
        /// hfDelete_EmployType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfDelete_EmployType;
        
        /// <summary>
        /// hfDeleteMessage_EmployType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfDeleteMessage_EmployType;
        
        /// <summary>
        /// hfCloseMessage_EmployType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfCloseMessage_EmployType;
        
        /// <summary>
        /// hfloadingPanel_GridEmployTypes_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridEmployTypes_EmployTypes;
        
        /// <summary>
        /// hfErrorType_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfErrorType_EmployTypes;
        
        /// <summary>
        /// hfConnectionError_EmployTypes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_EmployTypes;
    }
}
