//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class MainView {
    
    /// <summary>
    /// MainViewForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm MainViewForm;
    
    /// <summary>
    /// header_MainViewPart1_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl header_MainViewPart1_MainView;
    
    /// <summary>
    /// TlbMaximize_MainViewPart1_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbMaximize_MainViewPart1_MainView;
    
    /// <summary>
    /// tlbItemMaximize_TlbMaximize_MainViewPart1_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemMaximize_TlbMaximize_MainViewPart1_MainView;
    
    /// <summary>
    /// TlbRefresh_MainViewPart1_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_MainViewPart1_MainView;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_MainViewPart1_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_MainViewPart1_MainView;
    
    /// <summary>
    /// header_MainViewPart2_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl header_MainViewPart2_MainView;
    
    /// <summary>
    /// TlbMaximize_MainViewPart2_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbMaximize_MainViewPart2_MainView;
    
    /// <summary>
    /// tlbItemMaximize_TlbMaximize_MainViewPart2_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemMaximize_TlbMaximize_MainViewPart2_MainView;
    
    /// <summary>
    /// TlbRefresh_MainViewPart2_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_MainViewPart2_MainView;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_MainViewPart2_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_MainViewPart2_MainView;
    
    /// <summary>
    /// header_MainViewPart3_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl header_MainViewPart3_MainView;
    
    /// <summary>
    /// TlbMaximize_MainViewPart3_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbMaximize_MainViewPart3_MainView;
    
    /// <summary>
    /// tlbItemMaximize_TlbMaximize_MainViewPart3_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemMaximize_TlbMaximize_MainViewPart3_MainView;
    
    /// <summary>
    /// TlbRefresh_MainViewPart3_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_MainViewPart3_MainView;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_MainViewPart3_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_MainViewPart3_MainView;
    
    /// <summary>
    /// header_MainViewPart4_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl header_MainViewPart4_MainView;
    
    /// <summary>
    /// TlbMaximize_MainViewPart4_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbMaximize_MainViewPart4_MainView;
    
    /// <summary>
    /// tlbItemMaximize_TlbMaximize_MainViewPart4_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemMaximize_TlbMaximize_MainViewPart4_MainView;
    
    /// <summary>
    /// TlbRefresh_MainViewPart4_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_MainViewPart4_MainView;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_MainViewPart4_MainView control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_MainViewPart4_MainView;
    
    /// <summary>
    /// DialogMainViewMaximizedPart control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogMainViewMaximizedPart;
    
    /// <summary>
    /// DialogMainViewMaximizedPartheader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate DialogMainViewMaximizedPartheader;
    
    /// <summary>
    /// DialogMainViewMaximizedPartfooter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate DialogMainViewMaximizedPartfooter;
    
    /// <summary>
    /// DialogWaiting control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
    
    /// <summary>
    /// Img1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
}
