//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.Clock.Presentaion.WebForms {
    
    
    public partial class MasterUnderManagementPersonnelExeptionAccessView {
        
        /// <summary>
        /// MasterUnderManagementPersonnelExeptionAccessViewForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm MasterUnderManagementPersonnelExeptionAccessViewForm;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// lblManager_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblManager_MasterUnderManagementPersonnelExeptionAccessView;
        
        /// <summary>
        /// lblAccessGroup_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAccessGroup_MasterUnderManagementPersonnelExeptionAccessView;
  
        /// <summary>
        /// TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView;
        
        /// <summary>
        /// tlbItemRefresh_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView;
        
        /// <summary>
        /// tlbItemLast_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemLast_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView;
        
        /// <summary>
        /// tlbItemNext_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemNext_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView;
        
        /// <summary>
        /// tlbItemBefore_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemBefore_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView;
        
        /// <summary>
        /// tlbItemFirst_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFirst_TlbPaging_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView;
        
        /// <summary>
        /// footer_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell footer_GridUnderManagementPersonnelExeptionAccessView_MasterUnderManagementPersonnelExeptionAccessView;
        
        /// <summary>
        /// DialogWaiting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
        
        /// <summary>
        /// Img1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
    }
}
