//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class PersonnelMasterMonthlyOperation {
    
    /// <summary>
    /// PersonnelMasterMonthlyOperationForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm PersonnelMasterMonthlyOperationForm;
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// TlbPersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbPersonnelMasterMonthlyOperation;
    
    /// <summary>
    /// tlbItemHelp_TlbPersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemHelp_TlbPersonnelMasterMonthlyOperation;
    
    /// <summary>
    /// tlbItemFormReconstruction_TlbPersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFormReconstruction_TlbPersonnelMasterMonthlyOperation;
    
    /// <summary>
    /// tlbItemExit_TlbPersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbPersonnelMasterMonthlyOperation;
    
    /// <summary>
    /// TlbGridSchema_PersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbGridSchema_PersonnelMasterMonthlyOperation;
    
    /// <summary>
    /// tlbItemGridSchema_TlbGridSchema_PersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemGridSchema_TlbGridSchema_PersonnelMasterMonthlyOperation;
    
    /// <summary>
    /// TlbGraphicalSchema_PersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbGraphicalSchema_PersonnelMasterMonthlyOperation;
    
    /// <summary>
    /// tlbItemGraphicalSchema_TlbGraphicalSchema_PersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemGraphicalSchema_TlbGraphicalSchema_PersonnelMasterMonthlyOperation;
    
    /// <summary>
    /// DialogConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogConfirm;
    
    /// <summary>
    /// lblConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblConfirm;
    
    /// <summary>
    /// TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOkConfirm;
    
    /// <summary>
    /// tlbItemOk_TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOk_TlbOkConfirm;
    
    /// <summary>
    /// TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbCancelConfirm;
    
    /// <summary>
    /// tlbItemCancel_TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbCancelConfirm;
    
    /// <summary>
    /// hfCloseMessage_PersonnelMasterMonthlyOperation control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCloseMessage_PersonnelMasterMonthlyOperation;
}
