//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class ReportParametersConditions {
    
    /// <summary>
    /// Link2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlLink Link2;
    
    /// <summary>
    /// ReportParametersConditionsForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm ReportParametersConditionsForm;
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// TlbReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbReportParametersConditions;
    
    /// <summary>
    /// tlbItemRegister_TlbReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRegister_TlbReportParametersConditions;
    
    /// <summary>
    /// tlbItemClear_TlbReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemClear_TlbReportParametersConditions;
    
    /// <summary>
    /// tlbItemHelp_TlbReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemHelp_TlbReportParametersConditions;
    
    /// <summary>
    /// tlbItemExit_TlbReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbReportParametersConditions;
    
    /// <summary>
    /// lblField_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblField_ReportParametersConditions;
    
    /// <summary>
    /// lblFieldValue_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblFieldValue_ReportParametersConditions;
    
    /// <summary>
    /// CallBack_cmbField_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_cmbField_ReportParametersConditions;
    
    /// <summary>
    /// cmbField_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ComboBox cmbField_ReportParametersConditions;
    
    /// <summary>
    /// ErrorHiddenField_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_ReportParametersConditions;
    
    /// <summary>
    /// TlbInsertFieldToConditions_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbInsertFieldToConditions_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemInsertFiledToConditions_TlbInsertFieldToConditions_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemInsertFiledToConditions_TlbInsertFieldToConditions_ReportParametersConditions;
    
    /// <summary>
    /// TlbInsertFieldToOrders_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbInsertFieldToOrders_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemInsertFiledToOrders_TlbInsertFieldToOrders_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemInsertFiledToOrders_TlbInsertFieldToOrders_ReportParametersConditions;
    
    /// <summary>
    /// TlbInsertValueToConditions_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbInsertValueToConditions_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemInsertValueToConditions_TlbInsertToConditions_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemInsertValueToConditions_TlbInsertToConditions_ReportParametersConditions;
    
    /// <summary>
    /// CallBack_txtConditions_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_txtConditions_ReportParametersConditions;
    
    /// <summary>
    /// txtConditions_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTextArea txtConditions_ReportParametersConditions;
    
    /// <summary>
    /// ErrorHiddenField_txtConditions_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_txtConditions_ReportParametersConditions;
    
    /// <summary>
    /// hfConditionValue_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfConditionValue_ReportParametersConditions;
    
    /// <summary>
    /// hfTrafficConditionValue_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfTrafficConditionValue_ReportParametersConditions;
    
    /// <summary>
    /// hfConditionID_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfConditionID_ReportParametersConditions;
    
    /// <summary>
    /// TlbSum_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbSum_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemSum_TlbSum_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSum_TlbSum_ReportParametersConditions;
    
    /// <summary>
    /// TlbSubtraction_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbSubtraction_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemSubtraction_TlbSubtraction_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSubtraction_TlbSubtraction_ReportParametersConditions;
    
    /// <summary>
    /// TlbDivision_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbDivision_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemDivision_TlbDivision_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemDivision_TlbDivision_ReportParametersConditions;
    
    /// <summary>
    /// TlbMultiplication_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbMultiplication_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemMultiplication_TlbMultiplication_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemMultiplication_TlbMultiplication_ReportParametersConditions;
    
    /// <summary>
    /// TlbOpenBracket_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOpenBracket_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemOpenBracket_TlbOpenBracket_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOpenBracket_TlbOpenBracket_ReportParametersConditions;
    
    /// <summary>
    /// TlbCloseBracket_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbCloseBracket_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemCloseBracket_TlbOpenBracket_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCloseBracket_TlbOpenBracket_ReportParametersConditions;
    
    /// <summary>
    /// TlbLessThan_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbLessThan_ReportParametersConditions;
    
    /// <summary>
    /// tlbLessThan_TlbLessThan_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbLessThan_TlbLessThan_ReportParametersConditions;
    
    /// <summary>
    /// TlbGreaterThan_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbGreaterThan_ReportParametersConditions;
    
    /// <summary>
    /// tlbGreaterThan_TlbLessThan_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbGreaterThan_TlbLessThan_ReportParametersConditions;
    
    /// <summary>
    /// TlbLessEqualThan_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbLessEqualThan_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemLessEqualThan_TlbLessEqualThan_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemLessEqualThan_TlbLessEqualThan_ReportParametersConditions;
    
    /// <summary>
    /// TlbGreaterEqualThan_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbGreaterEqualThan_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemGreaterEqualThan_TlbGreaterEqualThan_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemGreaterEqualThan_TlbGreaterEqualThan_ReportParametersConditions;
    
    /// <summary>
    /// TlbEqual_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbEqual_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemEqual_TlbEqual_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemEqual_TlbEqual_ReportParametersConditions;
    
    /// <summary>
    /// TlbNotEqual_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbNotEqual_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemNotEqual_TlbNotEqual_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemNotEqual_TlbNotEqual_ReportParametersConditions;
    
    /// <summary>
    /// TlbOr_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOr_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemOr_TlbOr_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOr_TlbOr_ReportParametersConditions;
    
    /// <summary>
    /// TlbAnd_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbAnd_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemAnd_TlbAnd_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemAnd_TlbAnd_ReportParametersConditions;
    
    /// <summary>
    /// TlbOrderReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOrderReportParametersConditions;
    
    /// <summary>
    /// tlbItemClear_TlbOrderReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemClear_TlbOrderReportParametersConditions;
    
    /// <summary>
    /// CallBack_txtOrders_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_txtOrders_ReportParametersConditions;
    
    /// <summary>
    /// txtOrders_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTextArea txtOrders_ReportParametersConditions;
    
    /// <summary>
    /// ErrorHiddenField_txtOrders_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_txtOrders_ReportParametersConditions;
    
    /// <summary>
    /// hfOrderValue_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfOrderValue_ReportParametersConditions;
    
    /// <summary>
    /// hfOrderID_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfOrderID_ReportParametersConditions;
    
    /// <summary>
    /// TlbAscending_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbAscending_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemAscending_TlbAscending_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemAscending_TlbAscending_ReportParametersConditions;
    
    /// <summary>
    /// TlbDescending_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbDescending_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemDescending_TlbDescending_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemDescending_TlbDescending_ReportParametersConditions;
    
    /// <summary>
    /// TlbAndOrder_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbAndOrder_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemAndOrder_TlbAndOrder_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemAndOrder_TlbAndOrder_ReportParametersConditions;
    
    /// <summary>
    /// TlbGroupColumn_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbGroupColumn_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemSave_TlbGroupColumn_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSave_TlbGroupColumn_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemDelete_TlbGroupColumn_ReportParametersConditionsn control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemDelete_TlbGroupColumn_ReportParametersConditionsn;
    
    /// <summary>
    /// Td1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableCell Td1;
    
    /// <summary>
    /// TlbRefresh_GridGroupColumn_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_GridGroupColumn_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_GridGroupColumn_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridGroupColumn_ReportParametersConditions;
    
    /// <summary>
    /// CallBack_GridGroupColumns_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_GridGroupColumns_ReportParametersConditions;
    
    /// <summary>
    /// GridGroupColumns_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.DataGrid GridGroupColumns_ReportParametersConditions;
    
    /// <summary>
    /// ErrorHiddenField_GridGroupColumn_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_GridGroupColumn_ReportParametersConditions;
    
    /// <summary>
    /// TlbInterAction_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbInterAction_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemUp_TlbInterAction_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemUp_TlbInterAction_ReportParametersConditions;
    
    /// <summary>
    /// tlbItemDown_TlbInterAction_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemDown_TlbInterAction_ReportParametersConditions;
    
    /// <summary>
    /// Tr1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableRow Tr1;
    
    /// <summary>
    /// header_GroupColumnDetails_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl header_GroupColumnDetails_ReportParametersConditions;
    
    /// <summary>
    /// Tr2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableRow Tr2;
    
    /// <summary>
    /// lblGroupColumnName_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblGroupColumnName_ReportParametersConditions;
    
    /// <summary>
    /// Tr3 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableRow Tr3;
    
    /// <summary>
    /// CallBack_cmbGroupColumnField_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_cmbGroupColumnField_ReportParametersConditions;
    
    /// <summary>
    /// cmbGroupColumnField_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ComboBox cmbGroupColumnField_ReportParametersConditions;
    
    /// <summary>
    /// ErrorHiddenField_cmbGroupColumn_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_cmbGroupColumn_ReportParametersConditions;
    
    /// <summary>
    /// lblGroupingReportByNewPage_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblGroupingReportByNewPage_ReportParametersConditions;
    
    /// <summary>
    /// DialogWaiting control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
    
    /// <summary>
    /// Img1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
    
    /// <summary>
    /// hfTitle_DialogInternalReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfTitle_DialogInternalReportParametersConditions;
    
    /// <summary>
    /// hfErrorType_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfErrorType_ReportParametersConditions;
    
    /// <summary>
    /// hfConnectionError_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_ReportParametersConditions;
    
    /// <summary>
    /// hfheader_GroupColumn_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_GroupColumn_ReportParametersConditions;
    
    /// <summary>
    /// hfloadingPanel_GridGroupColumn_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridGroupColumn_ReportParametersConditions;
    
    /// <summary>
    /// hfheader_GroupColumnDetails_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_GroupColumnDetails_ReportParametersConditions;
    
    /// <summary>
    /// hfcmbAlarm_ReportParametersConditions control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfcmbAlarm_ReportParametersConditions;
}
