//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class RuleParameters {
    
    /// <summary>
    /// RuleParametersForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm RuleParametersForm;
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRuleParameters;
    
    /// <summary>
    /// tlbItemNew_TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemNew_TlbRuleParameters;
    
    /// <summary>
    /// tlbItemEdit_TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemEdit_TlbRuleParameters;
    
    /// <summary>
    /// tlbItemDelete_TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemDelete_TlbRuleParameters;
    
    /// <summary>
    /// tlbItemSave_TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSave_TlbRuleParameters;
    
    /// <summary>
    /// tlbItemCancel_TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbRuleParameters;
    
    /// <summary>
    /// tlbItemHelp_TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemHelp_TlbRuleParameters;
    
    /// <summary>
    /// tlbItemFormReconstruction_TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFormReconstruction_TlbRuleParameters;
    
    /// <summary>
    /// tlbItemExit_TlbRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbRuleParameters;
    
    /// <summary>
    /// TlbRefresh_GridRuleDateRanges_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_GridRuleDateRanges_RuleParameters;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_GridRuleDateRanges_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridRuleDateRanges_RuleParameters;
    
    /// <summary>
    /// CallBack_GridRuleDateRanges_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_GridRuleDateRanges_RuleParameters;
    
    /// <summary>
    /// GridRuleDateRanges_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.DataGrid GridRuleDateRanges_RuleParameters;
    
    /// <summary>
    /// ErrorHiddenField_RuleDateRanges_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_RuleDateRanges_RuleParameters;
    
    /// <summary>
    /// lblFromDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblFromDate_RuleParameters;
    
    /// <summary>
    /// Container_pdpFromDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Container_pdpFromDate_RuleParameters;
    
    /// <summary>
    /// pdpFromDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AspNetPersianDatePickup.PersianDatePickup pdpFromDate_RuleParameters;
    
    /// <summary>
    /// Container_gdpFromDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Container_gdpFromDate_RuleParameters;
    
    /// <summary>
    /// gdpFromDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Calendar gdpFromDate_RuleParameters;
    
    /// <summary>
    /// gCalFromDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Calendar gCalFromDate_RuleParameters;
    
    /// <summary>
    /// lblToDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblToDate_RuleParameters;
    
    /// <summary>
    /// Container_pdpToDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Container_pdpToDate_RuleParameters;
    
    /// <summary>
    /// pdpToDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AspNetPersianDatePickup.PersianDatePickup pdpToDate_RuleParameters;
    
    /// <summary>
    /// Container_gdpToDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Container_gdpToDate_RuleParameters;
    
    /// <summary>
    /// gdpToDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Calendar gdpToDate_RuleParameters;
    
    /// <summary>
    /// gCalToDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Calendar gCalToDate_RuleParameters;
    
    /// <summary>
    /// TlbRefresh_GridRuleParameters_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_GridRuleParameters_RuleParameters;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_GridRuleParameters_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridRuleParameters_RuleParameters;
    
    /// <summary>
    /// CallBack_GridRuleParameters_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_GridRuleParameters_RuleParameters;
    
    /// <summary>
    /// GridRuleParameters_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.DataGrid GridRuleParameters_RuleParameters;
    
    /// <summary>
    /// ErrorHiddenField_RuleParameters_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_RuleParameters_RuleParameters;
    
    /// <summary>
    /// TabStripRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.TabStrip TabStripRuleParametersTerms;
    
    /// <summary>
    /// tbNumeric_TabStripRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.TabStripTab tbNumeric_TabStripRuleParametersTerms;
    
    /// <summary>
    /// tbTime_TabStripRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.TabStripTab tbTime_TabStripRuleParametersTerms;
    
    /// <summary>
    /// tbDate_TabStripRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.TabStripTab tbDate_TabStripRuleParametersTerms;
    
    /// <summary>
    /// MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.MultiPage MultiPageRuleParametersTerms;
    
    /// <summary>
    /// pgvNumeric_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.PageView pgvNumeric_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// lblNumeric_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblNumeric_RuleParameters;
    
    /// <summary>
    /// txtNumeric_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputText txtNumeric_RuleParameters;
    
    /// <summary>
    /// TlbConfirm_pgvNumeric_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbConfirm_pgvNumeric_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// tlbItemConfirm_TlbConfirm_pgvNumeric_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemConfirm_TlbConfirm_pgvNumeric_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// pgvTime_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.PageView pgvTime_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// lblTime_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblTime_RuleParameters;
    
    /// <summary>
    /// lblNextDay_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblNextDay_RuleParameters;
    
    /// <summary>
    /// TlbConfirm_pgvTime_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbConfirm_pgvTime_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// tlbItemConfirm_TlbConfirm_pgvTime_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemConfirm_TlbConfirm_pgvTime_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// pgvDate_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.PageView pgvDate_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// lblDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblDate_RuleParameters;
    
    /// <summary>
    /// Container_pdpDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Container_pdpDate_RuleParameters;
    
    /// <summary>
    /// pdpDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::AspNetPersianDatePickup.PersianDatePickup pdpDate_RuleParameters;
    
    /// <summary>
    /// Container_gdpDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Container_gdpDate_RuleParameters;
    
    /// <summary>
    /// gdpDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Calendar gdpDate_RuleParameters;
    
    /// <summary>
    /// gCalDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Calendar gCalDate_RuleParameters;
    
    /// <summary>
    /// TlbConfirm_pgvDate_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbConfirm_pgvDate_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// tlbItemConfirm_TlbConfirm_pgvDate_MultiPageRuleParametersTerms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemConfirm_TlbConfirm_pgvDate_MultiPageRuleParametersTerms;
    
    /// <summary>
    /// lblRuleTitle_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblRuleTitle_RuleParameters;
    
    /// <summary>
    /// DialogConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogConfirm;
    
    /// <summary>
    /// lblConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblConfirm;
    
    /// <summary>
    /// TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOkConfirm;
    
    /// <summary>
    /// tlbItemOk_TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOk_TlbOkConfirm;
    
    /// <summary>
    /// TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbCancelConfirm;
    
    /// <summary>
    /// tlbItemCancel_TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbCancelConfirm;
    
    /// <summary>
    /// DialogWaiting control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
    
    /// <summary>
    /// Img1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
    
    /// <summary>
    /// hfheader_RuleDateRanges_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_RuleDateRanges_RuleParameters;
    
    /// <summary>
    /// hfheader_RuleParameters_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_RuleParameters_RuleParameters;
    
    /// <summary>
    /// hfView_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfView_RuleParameters;
    
    /// <summary>
    /// hfAdd_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfAdd_RuleParameters;
    
    /// <summary>
    /// hfEdit_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfEdit_RuleParameters;
    
    /// <summary>
    /// hfDelete_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfDelete_RuleParameters;
    
    /// <summary>
    /// hfDeleteMessage_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfDeleteMessage_RuleParameters;
    
    /// <summary>
    /// hfCloseMessage_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCloseMessage_RuleParameters;
    
    /// <summary>
    /// hfloadingPanel_GridRuleDateRanges_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridRuleDateRanges_RuleParameters;
    
    /// <summary>
    /// hfloadingPanel_GridRuleParameters_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridRuleParameters_RuleParameters;
    
    /// <summary>
    /// hfTitle_DialogRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfTitle_DialogRuleParameters;
    
    /// <summary>
    /// hfCurrentDate_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCurrentDate_RuleParameters;
    
    /// <summary>
    /// hfErrorType_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfErrorType_RuleParameters;
    
    /// <summary>
    /// hfConnectionError_RuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_RuleParameters;
}
