//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class RulesGroupUpdate {
    
    /// <summary>
    /// RulesGroupUpdateForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm RulesGroupUpdateForm;
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// contextMenu_trvRulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Menu contextMenu_trvRulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// AddItem_contextMenu_trvRulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.MenuItem AddItem_contextMenu_trvRulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// contextMenu_trvRules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Menu contextMenu_trvRules_RulesGroupUpdate;
    
    /// <summary>
    /// DeleteItem_contextMenu_trvRules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.MenuItem DeleteItem_contextMenu_trvRules_RulesGroupUpdate;
    
    /// <summary>
    /// TlbRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRulesGroupUpdate;
    
    /// <summary>
    /// tlbItemSave_TlbRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSave_TlbRulesGroupUpdate;
    
    /// <summary>
    /// tlbItemCancel_TlbRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbRulesGroupUpdate;
    
    /// <summary>
    /// tlbItemRuleParameteresRegulation_TlbRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRuleParameteresRegulation_TlbRulesGroupUpdate;
    
    /// <summary>
    /// tlbItemRuleGroupRulesParametersValidation_TlbRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRuleGroupRulesParametersValidation_TlbRulesGroupUpdate;
    
    /// <summary>
    /// tlbItemHelp_TlbRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemHelp_TlbRulesGroupUpdate;
    
    /// <summary>
    /// tlbItemFormReconstruction_TlbRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFormReconstruction_TlbRulesGroupUpdate;
    
    /// <summary>
    /// tlbItemExit_TlbRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbRulesGroupUpdate;
    
    /// <summary>
    /// lblRuleGroupName_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblRuleGroupName_RulesGroupUpdate;
    
    /// <summary>
    /// lblRuleGroupDescriptions_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblRuleGroupDescriptions_RulesGroupUpdate;
    
    /// <summary>
    /// txtRuleGroupName_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputText txtRuleGroupName_RulesGroupUpdate;
    
    /// <summary>
    /// Td2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableCell Td2;
    
    /// <summary>
    /// TlbRefresh_trvRulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_trvRulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_trvRulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_trvRulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// CallBack_trvRulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_trvRulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// trvRulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.TreeView trvRulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// ErrorHiddenField_RulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_RulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// TlbInterAction_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbInterAction_RulesGroupUpdate;
    
    /// <summary>
    /// tlbItemAdd_TlbInterAction_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemAdd_TlbInterAction_RulesGroupUpdate;
    
    /// <summary>
    /// tlbItemDelete_TlbInterAction_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemDelete_TlbInterAction_RulesGroupUpdate;
    
    /// <summary>
    /// TlbRefresh_trvRules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_trvRules_RulesGroupUpdate;
    
    /// <summary>
    /// tlbItemRefresh_TlbRefresh_trvRules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_trvRules_RulesGroupUpdate;
    
    /// <summary>
    /// CallBack_trvRules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_trvRules_RulesGroupUpdate;
    
    /// <summary>
    /// trvRules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.TreeView trvRules_RulesGroupUpdate;
    
    /// <summary>
    /// ErrorHiddenField_Rules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_Rules_RulesGroupUpdate;
    
    /// <summary>
    /// lblRuleTemplateDescription_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblRuleTemplateDescription_RulesGroupUpdate;
    
    /// <summary>
    /// lblRuleDescription_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblRuleDescription_RulesGroupUpdate;
    
    /// <summary>
    /// DialogRuleParameters control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogRuleParameters;
    
    /// <summary>
    /// DialogRuleParametersheader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate DialogRuleParametersheader;
    
    /// <summary>
    /// DialogRuleParametersfooter control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate DialogRuleParametersfooter;
    
    /// <summary>
    /// DialogConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogConfirm;
    
    /// <summary>
    /// lblConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblConfirm;
    
    /// <summary>
    /// TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOkConfirm;
    
    /// <summary>
    /// tlbItemOk_TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOk_TlbOkConfirm;
    
    /// <summary>
    /// TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbCancelConfirm;
    
    /// <summary>
    /// tlbItemCancel_TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbCancelConfirm;
    
    /// <summary>
    /// DialogWaiting control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
    
    /// <summary>
    /// hfheader_RulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_RulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// hfheader_Rules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_Rules_RulesGroupUpdate;
    
    /// <summary>
    /// hfloadingPanel_trvRulesTemplates_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_trvRulesTemplates_RulesGroupUpdate;
    
    /// <summary>
    /// hfloadingPanel_trvRules_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_trvRules_RulesGroupUpdate;
    
    /// <summary>
    /// hfView_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfView_RulesGroupUpdate;
    
    /// <summary>
    /// hfAdd_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfAdd_RulesGroupUpdate;
    
    /// <summary>
    /// hfEdit_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfEdit_RulesGroupUpdate;
    
    /// <summary>
    /// hfDelete_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfDelete_RulesGroupUpdate;
    
    /// <summary>
    /// hfDeleteMessage_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfDeleteMessage_RulesGroupUpdate;
    
    /// <summary>
    /// hfCloseMessage_RulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCloseMessage_RulesGroupUpdate;
    
    /// <summary>
    /// hfTitle_DialogRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfTitle_DialogRulesGroupUpdate;
    
    /// <summary>
    /// hfErrorType_DialogRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfErrorType_DialogRulesGroupUpdate;
    
    /// <summary>
    /// hfConnectionError_DialogRulesGroupUpdate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_DialogRulesGroupUpdate;
}
