//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class UpdateCalculationResult {
    
    /// <summary>
    /// UpdateCalculationResultForm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlForm UpdateCalculationResultForm;
    
    /// <summary>
    /// ScriptManager1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.ScriptManager ScriptManager1;
    
    /// <summary>
    /// TlbUpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbUpdateCalculationResult;
    
    /// <summary>
    /// tlbItemCalculationResultArchive_TlbUpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCalculationResultArchive_TlbUpdateCalculationResult;
    
    /// <summary>
    /// tlbItemGridSettings_TlbUpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemGridSettings_TlbUpdateCalculationResult;
    
    /// <summary>
    /// tlbItemHelp_TlbUpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemHelp_TlbUpdateCalculationResult;
    
    /// <summary>
    /// tlbItemFormReconstruction_TlbUpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFormReconstruction_TlbUpdateCalculationResult;
    
    /// <summary>
    /// tlbItemExit_TlbUpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbUpdateCalculationResult;
    
    /// <summary>
    /// imgbox_SearchByPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlImage imgbox_SearchByPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// lblPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// Td2 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableCell Td2;
    
    /// <summary>
    /// TlbPaging_PersonnelSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbPaging_PersonnelSearch_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemRefresh_TlbPaging_PersonnelSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbPaging_PersonnelSearch_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemFirst_TlbPaging_PersonnelSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFirst_TlbPaging_PersonnelSearch_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemBefore_TlbPaging_PersonnelSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemBefore_TlbPaging_PersonnelSearch_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemNext_TlbPaging_PersonnelSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemNext_TlbPaging_PersonnelSearch_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemLast_TlbPaging_PersonnelSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemLast_TlbPaging_PersonnelSearch_UpdateCalculationResult;
    
    /// <summary>
    /// CallBack_cmbPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_cmbPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// cmbPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ComboBox cmbPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// ItemTemplate_cmbPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate ItemTemplate_cmbPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// ErrorHiddenField_Personnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_Personnel_UpdateCalculationResult;
    
    /// <summary>
    /// hfPersonnelPageCount_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfPersonnelPageCount_UpdateCalculationResult;
    
    /// <summary>
    /// hfPersonnelCount_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfPersonnelCount_UpdateCalculationResult;
    
    /// <summary>
    /// txtPersonnelSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlInputText txtPersonnelSearch_UpdateCalculationResult;
    
    /// <summary>
    /// TlbSearchPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbSearchPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemSearch_TlbSearchPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSearch_TlbSearchPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// TlbAdvancedSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbAdvancedSearch_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemAdvancedSearch_TlbAdvancedSearch_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemAdvancedSearch_TlbAdvancedSearch_UpdateCalculationResult;
    
    /// <summary>
    /// lblYear_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblYear_UpdateCalculationResult;
    
    /// <summary>
    /// lblMonth_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblMonth_UpdateCalculationResult;
    
    /// <summary>
    /// cmbYear_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ComboBox cmbYear_UpdateCalculationResult;
    
    /// <summary>
    /// cmbMonth_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ComboBox cmbMonth_UpdateCalculationResult;
    
    /// <summary>
    /// TlbView_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbView_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemView_TlbView_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemView_TlbView_UpdateCalculationResult;
    
    /// <summary>
    /// CallBack_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.DataGrid GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// EditTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate EditTemplate;
    
    /// <summary>
    /// EditCommandTemplate control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ClientTemplate EditCommandTemplate;
    
    /// <summary>
    /// ErrorHiddenField_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_UpdateCalculationResult;
    
    /// <summary>
    /// hfCalculationResultCount_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCalculationResultCount_UpdateCalculationResult;
    
    /// <summary>
    /// hfCalculationResultPageCount_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCalculationResultPageCount_UpdateCalculationResult;
    
    /// <summary>
    /// Td1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableCell Td1;
    
    /// <summary>
    /// TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemRefresh_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemFirst_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFirst_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemBefore_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemBefore_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemNext_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemNext_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemLast_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemLast_TlbPaging_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// footer_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTableCell footer_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// DialogGridSettings control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogGridSettings;
    
    /// <summary>
    /// Table1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlTable Table1;
    
    /// <summary>
    /// TlbGridSettings control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbGridSettings;
    
    /// <summary>
    /// tlbItemSave_TlbGridSettings control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSave_TlbGridSettings;
    
    /// <summary>
    /// tlbItemExit_TlbGridSettings control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbGridSettings;
    
    /// <summary>
    /// lblSelectAll_GridSettings_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblSelectAll_GridSettings_UpdateCalculationResult;
    
    /// <summary>
    /// CallBack_GridSettings_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.CallBack CallBack_GridSettings_UpdateCalculationResult;
    
    /// <summary>
    /// GridSettings_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.DataGrid GridSettings_UpdateCalculationResult;
    
    /// <summary>
    /// ErrorHiddenField_GridSettings_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_GridSettings_UpdateCalculationResult;
    
    /// <summary>
    /// DialogOverrideCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogOverrideCalculationResult;
    
    /// <summary>
    /// lblOverrideCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblOverrideCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// lblOverrideCalculationResultDescription_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblOverrideCalculationResultDescription_UpdateCalculationResult;
    
    /// <summary>
    /// TlbOverrideCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOverrideCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// tlbItemOverrideCalculationResult_TlbOverrideCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOverrideCalculationResult_TlbOverrideCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// DialogConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogConfirm;
    
    /// <summary>
    /// lblConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Label lblConfirm;
    
    /// <summary>
    /// TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbOkConfirm;
    
    /// <summary>
    /// tlbItemOk_TlbOkConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOk_TlbOkConfirm;
    
    /// <summary>
    /// TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBar TlbCancelConfirm;
    
    /// <summary>
    /// tlbItemCancel_TlbCancelConfirm control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbCancelConfirm;
    
    /// <summary>
    /// DialogWaiting control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
    
    /// <summary>
    /// Img1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
    
    /// <summary>
    /// hfTitle_DialogUpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfTitle_DialogUpdateCalculationResult;
    
    /// <summary>
    /// hfheader_UpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_UpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// hfDeleteMessage_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfDeleteMessage_UpdateCalculationResult;
    
    /// <summary>
    /// hfCloseMessage_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCloseMessage_UpdateCalculationResult;
    
    /// <summary>
    /// hfCurrentYear_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCurrentYear_UpdateCalculationResult;
    
    /// <summary>
    /// hfCurrentMonth_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCurrentMonth_UpdateCalculationResult;
    
    /// <summary>
    /// hfCalculationResultPageSize_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCalculationResultPageSize_UpdateCalculationResult;
    
    /// <summary>
    /// hffooter_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hffooter_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// hfErrorType_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfErrorType_UpdateCalculationResult;
    
    /// <summary>
    /// hfConnectionError_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_UpdateCalculationResult;
    
    /// <summary>
    /// hfloadingPanel_GridUpdateCalculationResult_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridUpdateCalculationResult_UpdateCalculationResult;
    
    /// <summary>
    /// hfEdit_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfEdit_UpdateCalculationResult;
    
    /// <summary>
    /// hfDelete_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfDelete_UpdateCalculationResult;
    
    /// <summary>
    /// hfSave_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfSave_UpdateCalculationResult;
    
    /// <summary>
    /// hfCancel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCancel_UpdateCalculationResult;
    
    /// <summary>
    /// hfheader_SearchByPersonnelBox_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_SearchByPersonnelBox_UpdateCalculationResult;
    
    /// <summary>
    /// hfclmnName_cmbPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfclmnName_cmbPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// hfclmnBarCode_cmbPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfclmnBarCode_cmbPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// hfclmnCardNum_cmbPersonnel_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfclmnCardNum_cmbPersonnel_UpdateCalculationResult;
    
    /// <summary>
    /// hfPersonnelPageSize_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfPersonnelPageSize_UpdateCalculationResult;
    
    /// <summary>
    /// hfCurrentDate_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfCurrentDate_UpdateCalculationResult;
    
    /// <summary>
    /// hfheader_GridSettings_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfheader_GridSettings_UpdateCalculationResult;
    
    /// <summary>
    /// hfPersonnelCountTitle_UpdateCalculationResult control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.HiddenField hfPersonnelCountTitle_UpdateCalculationResult;
}
