//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Christoc.Modules.Atlas {
    
    
    public partial class View {
        
        /// <summary>
        /// MainForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl MainForm;
        
        /// <summary>
        /// ImgbtnPersian control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ImgbtnPersian;
        
        /// <summary>
        /// ImgbtnEnglish control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton ImgbtnEnglish;
        
        /// <summary>
        /// lblCurrentVersion control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCurrentVersion;
        
        /// <summary>
        /// lblCurrentUser control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblCurrentUser;
        
        /// <summary>
        /// TdImageButtonLogOut control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell TdImageButtonLogOut;
        
        /// <summary>
        /// imgbtnLogOut control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ImageButton imgbtnLogOut;
        
        /// <summary>
        /// NavBarMain_tr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableRow NavBarMain_tr;
        
        /// <summary>
        /// NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBar NavBarMain;
        
        /// <summary>
        /// nvbItemBasicDefinitions_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemBasicDefinitions_NavBarMain;
        
        /// <summary>
        /// nvbItemPersonnelIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPersonnelIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemEmployTypesIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemEmployTypesIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemCorporationsIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemCorporationsIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemDepartmentsIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemDepartmentsIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemPostsIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPostsIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemRulesGroupIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemRulesGroupIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemWorkGroupsIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemWorkGroupsIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemShiftPairTypesIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemShiftPairTypesIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemShiftIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemShiftIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemWorkHeatIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemWorkHeatIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemPreCardIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPreCardIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemPhysicianIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPhysicianIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemIllnessIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemIllnessIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemGradeIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemGradeIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemCostCenterIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemCostCenterIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemFlowGroupIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemFlowGroupIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemMissionLocationsIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemMissionLocationsIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemControlStationIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemControlStationIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemMachineIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemMachineIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemYearlyHolidaysIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemYearlyHolidaysIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemContractIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemContractIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemContractorsIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemContractorsIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemJustificationOperation_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemJustificationOperation_NavBarMain;
        
        /// <summary>
        /// nvbItemRegisteredRequests_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemRegisteredRequests_NavBarMain;
        
        /// <summary>
        /// nvbItemKartable_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemKartable_NavBarMain;
        
        /// <summary>
        /// nvbItemSurveyedRequests_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemSurveyedRequests_NavBarMain;
        
        /// <summary>
        /// nvbItemSpecialRequests_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemSpecialRequests_NavBarMain;
        
        /// <summary>
        /// nvbItemRequestSubstituteKartable_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemRequestSubstituteKartable_NavBarMain;
        
        /// <summary>
        /// nvbItemManagerMasterMonthlyOperationReport_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemManagerMasterMonthlyOperationReport_NavBarMain;
        
        /// <summary>
        /// nvbItemPersonnelMasterMonthlyOperationReport_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPersonnelMasterMonthlyOperationReport_NavBarMain;
        
        /// <summary>
        /// nvbItemWorkFlowsView_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemWorkFlowsView_NavBarMain;
        
        /// <summary>
        /// nvbItemWorkFlowDetail_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemWorkFlowDetail_NavBarMain;
        
        /// <summary>
        /// nvbItemMasterManagersIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemMasterManagersIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemSubstituteIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemSubstituteIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemOvertimePersonlist_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemOvertimePersonlist_NavBarMain;
        
        /// <summary>
        /// nvbItemPresenceAndAbsenceOperation_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPresenceAndAbsenceOperation_NavBarMain;
        
        /// <summary>
        /// nvbItemCalculationRangeDefinition_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemCalculationRangeDefinition_NavBarMain;
        
        /// <summary>
        /// nvbItemUiValidation_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemUiValidation_NavBarMain;
        
        /// <summary>
        /// nvbItemExceptionShiftsIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemExceptionShiftsIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemMasterLeaveRemains_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemMasterLeaveRemains_NavBarMain;
        
        /// <summary>
        /// nvbItemTrafficsControl_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemTrafficsControl_NavBarMain;
        
        /// <summary>
        /// nvbItemSentry_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemSentry_NavBarMain;
        
        /// <summary>
        /// nvbItemCalculationsResultsUpdate_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemCalculationsResultsUpdate_NavBarMain;
        
        /// <summary>
        /// nvbItemOvertime_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemOvertime_NavBarMain;
        
        /// <summary>
        /// nvbItemApprovalSchedulelist_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemApprovalSchedulelist_NavBarMain;
        
        /// <summary>
        /// nvbItemOvertimeEdarilist_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemOvertimeEdarilist_NavBarMain;
        
        /// <summary>
        /// nvbItemOvertimeSendFunctionlist_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemOvertimeSendFunctionlist_NavBarMain;
        
        /// <summary>
        /// nvbItemLateralOperations_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemLateralOperations_NavBarMain;
        
        /// <summary>
        /// nvbItemRolesIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemRolesIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemUsersIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemUsersIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemPasswordChange_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPasswordChange_NavBarMain;
        
        /// <summary>
        /// nvbItemPersonnelOrganizationFeaturesChange_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPersonnelOrganizationFeaturesChange_NavBarMain;
        
        /// <summary>
        /// nvbItemMasterPublicNews_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemMasterPublicNews_NavBarMain;
        
        /// <summary>
        /// nvbItemPrivateMessage_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPrivateMessage_NavBarMain;
        
        /// <summary>
        /// nvbItemCalculations_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemCalculations_NavBarMain;
        
        /// <summary>
        /// nvbItemPersonalUserSettings_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemPersonalUserSettings_NavBarMain;
        
        /// <summary>
        /// nvbItemManagementUserSettings_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemManagementUserSettings_NavBarMain;
        
        /// <summary>
        /// nvbItemOnlineTraffics_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemOnlineTraffics_NavBarMain;
        
        /// <summary>
        /// nvbItemWebRest_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemWebRest_NavBarMain;
        
        /// <summary>
        /// nvbItemReports_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemReports_NavBarMain;
        
        /// <summary>
        /// nvbItemReportsIntroduction_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemReportsIntroduction_NavBarMain;
        
        /// <summary>
        /// nvbItemSystemReports_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemSystemReports_NavBarMain;
        
        /// <summary>
        /// nvbItemDesignedReports_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemDesignedReports_NavBarMain;
        
        /// <summary>
        /// nvbItemRuleGenerator_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemRuleGenerator_NavBarMain;
        
        /// <summary>
        /// nvbItemRulesManagement_NavBarMain control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.NavBarItem nvbItemRulesManagement_NavBarMain;
        
        /// <summary>
        /// TabStripMenus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.TabStrip TabStripMenus;
        
        /// <summary>
        /// tbWelcome_TabStripMenus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.TabStripTab tbWelcome_TabStripMenus;
        
        /// <summary>
        /// MultiPageMenus control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.MultiPage MultiPageMenus;
        
        /// <summary>
        /// pgvWelcome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvWelcome;
        
        /// <summary>
        /// pgvShiftIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvShiftIntroduction;
        
        /// <summary>
        /// pgvDepartmentsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvDepartmentsIntroduction;
        
        /// <summary>
        /// pgvPostsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvPostsIntroduction;
        
        /// <summary>
        /// pgvEmployTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvEmployTypesIntroduction;
        
        /// <summary>
        /// pgvMissionLocationsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvMissionLocationsIntroduction;
        
        /// <summary>
        /// pgvExceptionShiftsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvExceptionShiftsIntroduction;
        
        /// <summary>
        /// pgvWorkGroupsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvWorkGroupsIntroduction;
        
        /// <summary>
        /// pgvPersonnelIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvPersonnelIntroduction;
        
        /// <summary>
        /// pgvWorkHeatIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvWorkHeatIntroduction;
        
        /// <summary>
        /// pgvControlStationIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvControlStationIntroduction;
        
        /// <summary>
        /// pgvMachineIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvMachineIntroduction;
        
        /// <summary>
        /// pgvMasterLeaveRemains control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvMasterLeaveRemains;
        
        /// <summary>
        /// pgvPersonnelOrganizationFeaturesChange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvPersonnelOrganizationFeaturesChange;
        
        /// <summary>
        /// pgvUsersIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvUsersIntroduction;
        
        /// <summary>
        /// pgvPreCardIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvPreCardIntroduction;
        
        /// <summary>
        /// pgvPasswordChange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvPasswordChange;
        
        /// <summary>
        /// pgvRolesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvRolesIntroduction;
        
        /// <summary>
        /// pgvManagerMasterMonthlyOperationReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvManagerMasterMonthlyOperationReport;
        
        /// <summary>
        /// pgvPersonnelMasterMonthlyOperationReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvPersonnelMasterMonthlyOperationReport;
        
        /// <summary>
        /// pgvMasterManagersIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvMasterManagersIntroduction;
        
        /// <summary>
        /// pgvWorkFlowsView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvWorkFlowsView;
        
        /// <summary>
        /// pgvSubstituteIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvSubstituteIntroduction;
        
        /// <summary>
        /// pgvPhysicianIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvPhysicianIntroduction;
        
        /// <summary>
        /// pgvIllnessIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvIllnessIntroduction;
        
        /// <summary>
        /// pgvGradeIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvGradeIntroduction;
        
        /// <summary>
        /// pgvCostCenterIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvCostCenterIntroduction;
        
        /// <summary>
        /// pgvFlowGroupIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvFlowGroupIntroduction;
        
        /// <summary>
        /// pgvCalculationRangeDefinition control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvCalculationRangeDefinition;
        
        /// <summary>
        /// pgvYearlyHolidaysIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvYearlyHolidaysIntroduction;
        
        /// <summary>
        /// pgvContractorsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvContractorsIntroduction;
        
        /// <summary>
        /// pgvRulesGroupIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvRulesGroupIntroduction;
        
        /// <summary>
        /// pgvReportsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvReportsIntroduction;
        
        /// <summary>
        /// pgvDesignedReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvDesignedReports;
        
        /// <summary>
        /// pgvTrafficsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvTrafficsControl;
        
        /// <summary>
        /// pgvMasterPublicNews control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvMasterPublicNews;
        
        /// <summary>
        /// pgvPrivateMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvPrivateMessage;
        
        /// <summary>
        /// pgvUiValidation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvUiValidation;
        
        /// <summary>
        /// pgvCalculations control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvCalculations;
        
        /// <summary>
        /// pgvCorporationsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvCorporationsIntroduction;
        
        /// <summary>
        /// pgvShiftPairTypesIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvShiftPairTypesIntroduction;
        
        /// <summary>
        /// pgvConceptRuleMasterOperation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvConceptRuleMasterOperation;
        
        /// <summary>
        /// pgvWorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvWorkFlowDetail;
        
        /// <summary>
        /// pgvContractIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.PageView pgvContractIntroduction;
        
        /// <summary>
        /// DialogLeaveBudget control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogLeaveBudget;
        
        /// <summary>
        /// DialogLeaveBudgetheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogLeaveBudgetheader;
        
        /// <summary>
        /// DialogLeaveBudgetfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogLeaveBudgetfooter;
        
        /// <summary>
        /// DialogUserInterfaceAccessLevels control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogUserInterfaceAccessLevels;
        
        /// <summary>
        /// DialogUserInterfaceAccessLevelsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUserInterfaceAccessLevelsheader;
        
        /// <summary>
        /// DialogUserInterfaceAccessLevelsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUserInterfaceAccessLevelsfooter;
        
        /// <summary>
        /// DialogPersonnelMainInformation control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogPersonnelMainInformation;
        
        /// <summary>
        /// DialogPersonnelMainInformationheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogPersonnelMainInformationheader;
        
        /// <summary>
        /// DialogPersonnelMainInformationfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogPersonnelMainInformationfooter;
        
        /// <summary>
        /// DialogPersonnelSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogPersonnelSearch;
        
        /// <summary>
        /// DialogPersonnelSearchheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogPersonnelSearchheader;
        
        /// <summary>
        /// DialogPersonnelSearchfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogPersonnelSearchfooter;
        
        /// <summary>
        /// DialogCalendar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogCalendar;
        
        /// <summary>
        /// DialogCalendarheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogCalendarheader;
        
        /// <summary>
        /// DialogCalendarfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogCalendarfooter;
        
        /// <summary>
        /// DialogExceptionShifts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogExceptionShifts;
        
        /// <summary>
        /// DialogExceptionShiftsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogExceptionShiftsheader;
        
        /// <summary>
        /// DialogExceptionShiftsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogExceptionShiftsfooter;
        
        /// <summary>
        /// DialogLoading control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogLoading;
        
        /// <summary>
        /// DialogMonthlyOperationGridSchema control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogMonthlyOperationGridSchema;
        
        /// <summary>
        /// DialogMonthlyOperationGridSchemaheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMonthlyOperationGridSchemaheader;
        
        /// <summary>
        /// DialogMonthlyOperationGridSchemafooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMonthlyOperationGridSchemafooter;
        
        /// <summary>
        /// DialogMonthlyOperationGanttChartSchema control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogMonthlyOperationGanttChartSchema;
        
        /// <summary>
        /// DialogMonthlyOperationGanttChartSchemaheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMonthlyOperationGanttChartSchemaheader;
        
        /// <summary>
        /// DialogMonthlyOperationGanttChartSchemafooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMonthlyOperationGanttChartSchemafooter;
        
        /// <summary>
        /// DialogUnderManagementPersonnel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogUnderManagementPersonnel;
        
        /// <summary>
        /// DialogUnderManagementPersonnelheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUnderManagementPersonnelheader;
        
        /// <summary>
        /// DialogUnderManagementPersonnelfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUnderManagementPersonnelfooter;
        
        /// <summary>
        /// DialogKartable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogKartable;
        
        /// <summary>
        /// DialogKartableheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogKartableheader;
        
        /// <summary>
        /// DialogKartablefooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogKartablefooter;
        
        /// <summary>
        /// DialogEndorsementFlowState control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogEndorsementFlowState;
        
        /// <summary>
        /// DialogEndorsementFlowStateheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogEndorsementFlowStateheader;
        
        /// <summary>
        /// DialogEndorsementFlowStatefooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogEndorsementFlowStatefooter;
        
        /// <summary>
        /// DialogRegisteredRequests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogRegisteredRequests;
        
        /// <summary>
        /// DialogRegisteredRequestsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRegisteredRequestsheader;
        
        /// <summary>
        /// DialogRegisteredRequestsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRegisteredRequestsfooter;
        
        /// <summary>
        /// DialogCalculationRange control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogCalculationRange;
        
        /// <summary>
        /// DialogCalculationRangeheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogCalculationRangeheader;
        
        /// <summary>
        /// DialogCalculationRangefooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogCalculationRangefooter;
        
        /// <summary>
        /// DialogRulesGroupUpdate control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogRulesGroupUpdate;
        
        /// <summary>
        /// DialogRulesGroupUpdateheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRulesGroupUpdateheader;
        
        /// <summary>
        /// DialogRulesGroupUpdatefooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRulesGroupUpdatefooter;
        
        /// <summary>
        /// DialogReportParameters control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogReportParameters;
        
        /// <summary>
        /// DialogReportParametersheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogReportParametersheader;
        
        /// <summary>
        /// DialogReportParametersfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogReportParametersfooter;
        
        /// <summary>
        /// DialogSubstituteSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogSubstituteSettings;
        
        /// <summary>
        /// DialogSubstituteSettingsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogSubstituteSettingsheader;
        
        /// <summary>
        /// DialogSubstituteSettingsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogSubstituteSettingsfooter;
        
        /// <summary>
        /// DialogOperators control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogOperators;
        
        /// <summary>
        /// DialogOperatorsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogOperatorsheader;
        
        /// <summary>
        /// DialogOperatorsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogOperatorsfooter;
        
        /// <summary>
        /// DialogLeaveReserve control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogLeaveReserve;
        
        /// <summary>
        /// DialogLeaveReserveheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogLeaveReserveheader;
        
        /// <summary>
        /// DialogLeaveReservefooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogLeaveReservefooter;
        
        /// <summary>
        /// DialogMasterRulesView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogMasterRulesView;
        
        /// <summary>
        /// DialogMasterRulesViewheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMasterRulesViewheader;
        
        /// <summary>
        /// DialogMasterRulesViewfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMasterRulesViewfooter;
        
        /// <summary>
        /// DialogMasterDataAccessLevels control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogMasterDataAccessLevels;
        
        /// <summary>
        /// DialogMasterDataAccessLevelsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMasterDataAccessLevelsheader;
        
        /// <summary>
        /// DialogMasterDataAccessLevelsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMasterDataAccessLevelsfooter;
        
        /// <summary>
        /// DialogSendPrivateMessage control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogSendPrivateMessage;
        
        /// <summary>
        /// DialogSendPrivateMessageheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogSendPrivateMessageheader;
        
        /// <summary>
        /// DialogSendPrivateMessagefooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogSendPrivateMessagefooter;
        
        /// <summary>
        /// DialogUiValidationRules control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogUiValidationRules;
        
        /// <summary>
        /// DialogUiValidationRulesheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUiValidationRulesheader;
        
        /// <summary>
        /// DialogUiValidationRulesfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUiValidationRulesfooter;
        
        /// <summary>
        /// DialogUserSettings control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogUserSettings;
        
        /// <summary>
        /// DialogUserSettingsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUserSettingsheader;
        
        /// <summary>
        /// DialogUserSettingsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUserSettingsfooter;
        
        /// <summary>
        /// DialogTrafficsTransfer control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogTrafficsTransfer;
        
        /// <summary>
        /// DialogTrafficsTransferheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogTrafficsTransferheader;
        
        /// <summary>
        /// DialogTrafficsTransferfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogTrafficsTransferfooter;
        
        /// <summary>
        /// DialogSystemReports control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogSystemReports;
        
        /// <summary>
        /// DialogSystemReportsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogSystemReportsheader;
        
        /// <summary>
        /// DialogSystemReportsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogSystemReportsfooter;
        
        /// <summary>
        /// DialogMonthlyExceptionShifts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogMonthlyExceptionShifts;
        
        /// <summary>
        /// DialogMonthlyExceptionShiftsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMonthlyExceptionShiftsheader;
        
        /// <summary>
        /// DialogMonthlyExceptionShiftsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogMonthlyExceptionShiftsfooter;
        
        /// <summary>
        /// DialogUpdateCalculationResult control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogUpdateCalculationResult;
        
        /// <summary>
        /// DialogUpdateCalculationResultheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUpdateCalculationResultheader;
        
        /// <summary>
        /// DialogUpdateCalculationResultfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogUpdateCalculationResultfooter;
        
        /// <summary>
        /// DialogDesignedReportsSelectColumn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogDesignedReportsSelectColumn;
        
        /// <summary>
        /// DialogDesignedReportsSelectColumnsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogDesignedReportsSelectColumnsheader;
        
        /// <summary>
        /// DialogDesignedReportsSelectColumnfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogDesignedReportsSelectColumnfooter;
        
        /// <summary>
        /// DialogReportParametersConditions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogReportParametersConditions;
        
        /// <summary>
        /// DialogReportParametersConditionsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogReportParametersConditionsheader;
        
        /// <summary>
        /// DialogReportParametersConditionsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogReportParametersConditionsfooter;
        
        /// <summary>
        /// DialogDefinePhysicians control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogDefinePhysicians;
        
        /// <summary>
        /// DialogDefinePhysiciansheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogDefinePhysiciansheader;
        
        /// <summary>
        /// DialogDefinePhysiciansfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogDefinePhysiciansfooter;
        
        /// <summary>
        /// DialogDefineIllness control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogDefineIllness;
        
        /// <summary>
        /// DialogDefineIllnessheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogDefineIllnessheader;
        
        /// <summary>
        /// DialogDefineIllnessfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogDefineIllnessfooter;
        
        /// <summary>
        /// DialogConceptsManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogConceptsManagement;
        
        /// <summary>
        /// DialogConceptsManagementheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogConceptsManagementheader;
        
        /// <summary>
        /// DialogConceptsManagementfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogConceptsManagementfooter;
        
        /// <summary>
        /// DialogRuleGenerator control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogRuleGenerator;
        
        /// <summary>
        /// DialogRuleGeneratorheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRuleGeneratorheader;
        
        /// <summary>
        /// DialogRuleGeneratorfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRuleGeneratorfooter;
        
        /// <summary>
        /// DialogRulesManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogRulesManagement;
        
        /// <summary>
        /// DialogRulesManagementheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRulesManagementheader;
        
        /// <summary>
        /// DialogRulesManagementfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRulesManagementfooter;
        
        /// <summary>
        /// DialogConceptRuleEditor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogConceptRuleEditor;
        
        /// <summary>
        /// DialogConceptRuleEditorheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogConceptRuleEditorheader;
        
        /// <summary>
        /// DialogConceptRuleEditorfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogConceptRuleEditorfooter;
        
        /// <summary>
        /// DialogExpressionsManagement control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogExpressionsManagement;
        
        /// <summary>
        /// DialogExpressionsManagementheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogExpressionsManagementheader;
        
        /// <summary>
        /// DialogExpressionsManagementfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogExpressionsManagementfooter;
        
        /// <summary>
        /// DialogOnlineTraffics control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogOnlineTraffics;
        
        /// <summary>
        /// DialogOnlineTrafficsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogOnlineTrafficsheader;
        
        /// <summary>
        /// DialogOnlineTrafficsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogOnlineTrafficsfooter;
        
        /// <summary>
        /// DialogFlowConditions control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogFlowConditions;
        
        /// <summary>
        /// DialogFlowConditionsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogFlowConditionsheader;
        
        /// <summary>
        /// DialogFlowConditionsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogFlowConditionsfooter;
        
        /// <summary>
        /// DialogRequestHistory control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogRequestHistory;
        
        /// <summary>
        /// DialogRequestHistoryheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRequestHistoryheader;
        
        /// <summary>
        /// DialogRequestHistoryfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRequestHistoryfooter;
        
        /// <summary>
        /// DialogRulePrecards control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogRulePrecards;
        
        /// <summary>
        /// DialogRulePrecardsheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRulePrecardsheader;
        
        /// <summary>
        /// DialogRulePrecardsfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRulePrecardsfooter;
        
        /// <summary>
        /// DialogWorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogWorkFlowDetail;
        
        /// <summary>
        /// DialogWorkFlowDetailheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogWorkFlowDetailheader;
        
        /// <summary>
        /// DialogWorkFlowDetailfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogWorkFlowDetailfooter;
        
        /// <summary>
        /// DialogRequestRefrence control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogRequestRefrence;
        
        /// <summary>
        /// DialogRequestRefrenceheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRequestRefrenceheader;
        
        /// <summary>
        /// DialogRequestRefrencefooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogRequestRefrencefooter;
        
        /// <summary>
        /// hfdmItemPersonnelMasterMonthlyOperationReport_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemPersonnelMasterMonthlyOperationReport_DockMenu;
        
        /// <summary>
        /// hfdmItemManagerMasterMonthlyOperationReport_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemManagerMasterMonthlyOperationReport_DockMenu;
        
        /// <summary>
        /// hfdmItemPersonnelIntroduction_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemPersonnelIntroduction_DockMenu;
        
        /// <summary>
        /// hfdmItemReportsIntroduction_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemReportsIntroduction_DockMenu;
        
        /// <summary>
        /// hfdmItemKartable_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemKartable_DockMenu;
        
        /// <summary>
        /// hfdmItemSurveyedRequests_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemSurveyedRequests_DockMenu;
        
        /// <summary>
        /// hfdmItemRegisteredRequests_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemRegisteredRequests_DockMenu;
        
        /// <summary>
        /// hfdmItemTrafficOperationByOperator_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemTrafficOperationByOperator_DockMenu;
        
        /// <summary>
        /// hfdmItemWorkFlowsView_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemWorkFlowsView_DockMenu;
        
        /// <summary>
        /// hfdmItemWelcome_DockMenu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfdmItemWelcome_DockMenu;
        
        /// <summary>
        /// hfErrorType_MainForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfErrorType_MainForm;
        
        /// <summary>
        /// hfConnectionError_MainForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_MainForm;
        
        /// <summary>
        /// hfCurrentUILangID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentUILangID;
        
        /// <summary>
        /// hfCurrentSysLangID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfCurrentSysLangID;
        
        /// <summary>
        /// hfTitle_qlItemHome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemHome;
        
        /// <summary>
        /// hfTitle_qlItemWorkFlowsView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemWorkFlowsView;
        
        /// <summary>
        /// hfTitle_qlItemTrafficsControl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemTrafficsControl;
        
        /// <summary>
        /// hfTitle_qlItemRegisteredRequests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemRegisteredRequests;
        
        /// <summary>
        /// hfTitle_qlItemSurveyedRequests control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemSurveyedRequests;
        
        /// <summary>
        /// hfTitle_qlItemKartable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemKartable;
        
        /// <summary>
        /// hfTitle_qlItemReportsIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemReportsIntroduction;
        
        /// <summary>
        /// hfTitle_qlItemPersonnelIntroduction control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemPersonnelIntroduction;
        
        /// <summary>
        /// hfTitle_qlItemManagerMasterMonthlyOperationReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemManagerMasterMonthlyOperationReport;
        
        /// <summary>
        /// hfTitle_qlItemPersonnelMasterMonthlyOperationReport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_qlItemPersonnelMasterMonthlyOperationReport;
        
        /// <summary>
        /// hfAccessNoAllowdNavBarItemsList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfAccessNoAllowdNavBarItemsList;
        
        /// <summary>
        /// hfMonthlyOperationSchema_MainForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfMonthlyOperationSchema_MainForm;
    }
}
