//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTS.Clock.Presentaion.WebForms {
    
    
    public partial class WorkFlowDetail {
        
        /// <summary>
        /// WorkFlowDetailForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm WorkFlowDetailForm;
        
        /// <summary>
        /// ScriptManager1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.ScriptManager ScriptManager1;
        
        /// <summary>
        /// TlbWorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbWorkFlowDetail;
        
        /// <summary>
        /// tlbItemHelp_TlbWorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemHelp_TlbWorkFlowDetail;
        
        /// <summary>
        /// tlbItemFormReconstruction_TlbWorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFormReconstruction_TlbWorkFlowDetail;
        
        /// <summary>
        /// tlbItemExit_TlbWorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemExit_TlbWorkFlowDetail;
        
        /// <summary>
        /// lblSearchField_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSearchField_WorkFlowDetail;
        
        /// <summary>
        /// lblSearchTerm_WorkFlowDetail1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblSearchTerm_WorkFlowDetail1;
        
        /// <summary>
        /// CallBack_cmbSearchField_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_cmbSearchField_WorkFlowDetail;
        
        /// <summary>
        /// cmbSearchField_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ComboBox cmbSearchField_WorkFlowDetail;
        
        /// <summary>
        /// ErrorHiddenField_WorkFlowDetailSearchField control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_WorkFlowDetailSearchField;
        
        /// <summary>
        /// TlbView_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbView_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemView_TlbView_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemView_TlbView_WorkFlowDetail;
        
        /// <summary>
        /// lblMatchWholWord_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMatchWholWord_WorkFlowDetail;
        
        /// <summary>
        /// divPersonnelSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divPersonnelSearch_WorkFlowDetail;
        
        /// <summary>
        /// imgbox_SearchByPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage imgbox_SearchByPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// lblPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// Td2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTableCell Td2;
        
        /// <summary>
        /// TlbPaging_PersonnelSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbPaging_PersonnelSearch_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemRefresh_TlbPaging_PersonnelSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbPaging_PersonnelSearch_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemFirst_TlbPaging_PersonnelSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemFirst_TlbPaging_PersonnelSearch_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemBefore_TlbPaging_PersonnelSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemBefore_TlbPaging_PersonnelSearch_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemNext_TlbPaging_PersonnelSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemNext_TlbPaging_PersonnelSearch_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemLast_TlbPaging_PersonnelSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemLast_TlbPaging_PersonnelSearch_WorkFlowDetail;
        
        /// <summary>
        /// CallBack_cmbPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_cmbPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// cmbPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ComboBox cmbPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// ItemTemplate_cmbPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate ItemTemplate_cmbPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// ErrorHiddenField_Personnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_Personnel_WorkFlowDetail;
        
        /// <summary>
        /// hfPersonnelPageCount_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfPersonnelPageCount_WorkFlowDetail;
        
        /// <summary>
        /// txtPersonnelSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtPersonnelSearch_WorkFlowDetail;
        
        /// <summary>
        /// TlbSearchPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbSearchPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemSearch_TlbSearchPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemSearch_TlbSearchPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// TlbViewWorkFlow_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbViewWorkFlow_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemView_TlbViewWorkFlow_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemView_TlbViewWorkFlow_WorkFlowDetail;
        
        /// <summary>
        /// TlbAdvancedSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbAdvancedSearch_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemAdvancedSearch_TlbAdvancedSearch_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemAdvancedSearch_TlbAdvancedSearch_WorkFlowDetail;
        
        /// <summary>
        /// TlbRefresh_GridManagers_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_GridManagers_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemRefresh_TlbRefresh_GridManagers_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridManagers_WorkFlowDetail;
        
        /// <summary>
        /// CallBack_GridManagers_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_GridManagers_WorkFlowDetail;
        
        /// <summary>
        /// GridManagers_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.DataGrid GridManagers_WorkFlowDetail;
        
        /// <summary>
        /// ErrorHiddenField_Managers_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_Managers_WorkFlowDetail;
        
        /// <summary>
        /// TlbGridWorkFlows_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbGridWorkFlows_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemUnderManagmentPersonnelsRetrieve_TlbGridWorkFlows control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemUnderManagmentPersonnelsRetrieve_TlbGridWorkFlows;
        
        /// <summary>
        /// tlbItemRefresh_TlbRefresh_GridWorkFlows_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridWorkFlows_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemAccessLevelView_TlbWorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemAccessLevelView_TlbWorkFlowDetail;
        
        /// <summary>
        /// CallBack_GridWorkFlows_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_GridWorkFlows_WorkFlowDetail;
        
        /// <summary>
        /// GridWorkFlows_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.DataGrid GridWorkFlows_WorkFlowDetail;
        
        /// <summary>
        /// ErrorHiddenField_WorkFlows_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_WorkFlows_WorkFlowDetail;
        
        /// <summary>
        /// TlbRefresh_GridOperator_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_GridOperator_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemRefresh_TlbRefresh_GridOperator_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridOperator_WorkFlowDetail;
        
        /// <summary>
        /// CallBack_GridOperator_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_GridOperator_WorkFlowDetail;
        
        /// <summary>
        /// GridOperator_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.DataGrid GridOperator_WorkFlowDetail;
        
        /// <summary>
        /// ErrorHiddenField_Operator_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_Operator_WorkFlowDetail;
        
        /// <summary>
        /// TlbRefresh_GridSubstitute_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_GridSubstitute_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemRefresh_TlbRefresh_GridSubstitute_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_GridSubstitute_WorkFlowDetail;
        
        /// <summary>
        /// CallBack_GridSubstitute_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_GridSubstitute_WorkFlowDetail;
        
        /// <summary>
        /// GridSubstitute_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.DataGrid GridSubstitute_WorkFlowDetail;
        
        /// <summary>
        /// ErrorHiddenField_Substitute_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_Substitute_WorkFlowDetail;
        
        /// <summary>
        /// TlbRefresh_trvUnderManagementPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbRefresh_trvUnderManagementPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// tlbItemRefresh_TlbRefresh_trvUnderManagementPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemRefresh_TlbRefresh_trvUnderManagementPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// CallBack_trvUnderManagementPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_trvUnderManagementPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// trvUnderManagementPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.TreeView trvUnderManagementPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// ErrorHiddenField_UnderManagementPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_UnderManagementPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// DialogConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogConfirm;
        
        /// <summary>
        /// lblConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblConfirm;
        
        /// <summary>
        /// TlbOkConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbOkConfirm;
        
        /// <summary>
        /// tlbItemOk_TlbOkConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemOk_TlbOkConfirm;
        
        /// <summary>
        /// TlbCancelConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBar TlbCancelConfirm;
        
        /// <summary>
        /// tlbItemCancel_TlbCancelConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ToolBarItem tlbItemCancel_TlbCancelConfirm;
        
        /// <summary>
        /// DialogAccessLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogAccessLevel;
        
        /// <summary>
        /// DialogAccessLevelheader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogAccessLevelheader;
        
        /// <summary>
        /// DialogAccessLevelfooter control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.ClientTemplate DialogAccessLevelfooter;
        
        /// <summary>
        /// Table1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTable Table1;
        
        /// <summary>
        /// CallBack_trvAccessLevel_AccessGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.CallBack CallBack_trvAccessLevel_AccessGroups;
        
        /// <summary>
        /// trvAccessLevel_AccessGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.TreeView trvAccessLevel_AccessGroups;
        
        /// <summary>
        /// hfAccessLevelsList_AccessGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfAccessLevelsList_AccessGroups;
        
        /// <summary>
        /// ErrorHiddenField_AccessLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField ErrorHiddenField_AccessLevel;
        
        /// <summary>
        /// DialogWaiting control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::ComponentArt.Web.UI.Dialog DialogWaiting;
        
        /// <summary>
        /// Img1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlImage Img1;
        
        /// <summary>
        /// hfheader_Managers_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_Managers_WorkFlowDetail;
        
        /// <summary>
        /// hfheader_WorkFlows_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_WorkFlows_WorkFlowDetail;
        
        /// <summary>
        /// hfheader_Operator_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_Operator_WorkFlowDetail;
        
        /// <summary>
        /// hfheader_Substitute_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_Substitute_WorkFlowDetail;
        
        /// <summary>
        /// hfheader_UnderManagementPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_UnderManagementPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// hfCloseMessage__WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfCloseMessage__WorkFlowDetail;
        
        /// <summary>
        /// hfloadingPanel_GridOperator_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridOperator_WorkFlowDetail;
        
        /// <summary>
        /// hfloadingPanel_GridWorkFlows_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridWorkFlows_WorkFlowDetail;
        
        /// <summary>
        /// hfloadingPanel_GridManagers_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridManagers_WorkFlowDetail;
        
        /// <summary>
        /// hfloadingPanel_trvUnderManagementPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_trvUnderManagementPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// hfloadingPanel_GridSubstitute_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_GridSubstitute_WorkFlowDetail;
        
        /// <summary>
        /// hfcmbAlarm_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfcmbAlarm_WorkFlowDetail;
        
        /// <summary>
        /// hfheader_AccessLevelBox_AccessGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_AccessLevelBox_AccessGroups;
        
        /// <summary>
        /// hfloadingPanel_trvAccessLevel_AccessGroups control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfloadingPanel_trvAccessLevel_AccessGroups;
        
        /// <summary>
        /// hfTitle_DialogAccessLevel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_DialogAccessLevel;
        
        /// <summary>
        /// hfheader_SearchByPersonnelBox_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfheader_SearchByPersonnelBox_WorkFlowDetail;
        
        /// <summary>
        /// hfPersonnelPageSize_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfPersonnelPageSize_WorkFlowDetail;
        
        /// <summary>
        /// hfErrorType_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfErrorType_WorkFlowDetail;
        
        /// <summary>
        /// hfConnectionError_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfConnectionError_WorkFlowDetail;
        
        /// <summary>
        /// hfclmnBarCode_cmbPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfclmnBarCode_cmbPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// hfclmnName_cmbPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfclmnName_cmbPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// hfclmnCardNum_cmbPersonnel_WorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfclmnCardNum_cmbPersonnel_WorkFlowDetail;
        
        /// <summary>
        /// hfTitle_DialogWorkFlowDetail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hfTitle_DialogWorkFlowDetail;
    }
}
